version: "3"

services:
  consul:
    image: consul:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /Users/stackcats/data/consul:/consul/data
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600"
    command: agent -server -bootstrap-expect=1  -bind=127.0.0.1 -client=0.0.0.0 -ui
    networks:
      - swarm_network
    environment:
      CONSUL_UI_BETA: "true"

networks:  
  swarm_network:
    external:
      name: stackcats