version: "3"  

services:  
  nats:
    image: nats:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - swarm_network

networks:  
  swarm_network:
    external:
      name: stackcats