version: "3"

services:
  portainer:
    image: portainer/portainer:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/stackcats/data/portainer:/data
    networks:
      - swarm_network

networks:  
  swarm_network:
    external:
      name: stackcats